services:
  # Serviço para o PHP (Laravel)
  app:
    build:
      context: ./pastelaria-api
    container_name: pastelaria-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./pastelaria-api:/var/www
    networks:
      - app_network
    depends_on:
      - db
    expose:
      - "9000"
    environment:
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}

  # Serviço para o banco de dados MySQL - Banco de dados de produção
  db:
    image: mysql:9.1
    container_name: pastelaria-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  # Serviço para o banco de dados MySQL (para testes)
  db_test:
    image: mysql:9.1
    container_name: pastelaria-db-test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_TEST}
    volumes:
      - db_test_data:/var/lib/mysql
    networks:
      - app_network

  # Serviço para o Nginx
  nginx:
    image: nginx:latest
    container_name: pastelaria-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./pastelaria-api:/var/www
      #- ./frontend:/var/www/frontent
    ports:
      - "8000:${NGINX_PORT}"  # Servindo na porta 80
    depends_on:
      - app
    networks:
      - app_network

# Volumes para persistir dados
volumes:
  db_data:
    driver: local
  db_test_data:
    driver: local

# Redes para comunicação entre os containers
networks:
  app_network:
    driver: bridge
